(function(a){CTXS.ExtensionAPI.addPlugin({name:"nsg-epa",initialize:function(){CTXS.ExtensionAPI.addCustomAuthLabelHandler({getLabelTypeName:function(){return"nsg-epa"},getLabelTypeMarkup:function(b){UnsetCookie("NSC_ERRM");var c=a("<div></div>"),d=a("<div></div>").attr({id:"nsepadiv",style:"visibility:hidden"});c.append(d);d=a("<p></p>").attr({id:"epa_title","class":"main-text"});ns_getcookie("NSC_AAAC")?d.addClass("_ctxstxt_postepa_title"):d.addClass("_ctxstxt_epa_title");c.append(d);d=a("<div></div>").attr({"class":"detail-text _ctxstxt_Epa_Pre_Reqm_Msg"});
c.append(d);d=a("<br/>");c.append(d);d=a("<div></div>").attr({"class":"detail-text _ctxstxt_Checking_if_the_plug-in_is_installed",id:"PluginCheck"});c.append(d);d=a("<br/>");c.append(d);d=a("<div></div>").attr({"class":"detail-text",id:"timer"});c.append(d);c.ctxsLocalize();null!=b.input.text&&""!=b.input.text.initialValue&&(secureToken=base64decode(b.input.text.initialValue),isEpaFactor=!0,"EPA-Factor"==secureToken&&(secureToken=""));return c},parseAsType:function(){return"plain"}});CTXS.ExtensionAPI.addCustomCredentialHandler({getCredentialTypeName:function(){return"nsg-epa"},
getDataToAutoPost:function(b,c,d){epa_form=b;success_callback_global=d;c=a("<a>"+_localize("Skip Check")+"</a>").attr({id:"skipbutton","class":"default button",style:"display:none; cursor:pointer"});a(c).click(function(b){b.preventDefault();window.clearInterval(util.pollNSId);SetErrMsg(_localize("user_skip_epa_msg"));!secureToken&&CTXS.getCookie("NSC_AAAC")?a.ctxsAjax({store:null,type:"GET",url:"/epaskip",dataType:"text",async:!1,success:function(a,b,c){console.log("Epaskip successful!");epa_success_callback("epaskip")},
error:function(a,b,c){console.log("Epaskip request failed! Reason: "+b)},refreshSession:!0}):(SetErrMsg(_localize("user_skip_epa_msg")),epa_success_callback("failure"))});CTXS.getCookie("NSC_EPAC")?c.hide():c.show();b.append(c);detectEpaComponent()}});CTXS.ExtensionAPI.addCustomAuthLabelHandler({getLabelTypeName:function(){return"nsg-epa-failure"},getLabelTypeMarkup:function(b){b=a("<div></div>");var c=a("<div></div>").attr({id:"epa-failure-heading","class":"main-text error _ctxstxt_EPAAccessDenied"});
b.append(c);c=a("<div></div>").attr({"class":"detail-text _ctxstxt_EPA_not_meet_reqm_msg"});b.append(c);c=a("<br/>");b.append(c);c=a("<div></div>").attr({"class":"detail-text _ctxstxt_EPA_MoreInfoMsg"});b.append(c);c=a("<br/>");b.append(c);var c=a("<table></table>").attr({id:"epaErrorTable"}),d=a("<tr></tr>").append(a("<td></td>").attr({width:"20%"}),a("<td></td>").attr({width:"80%"}));d.find("td").append(a("<span></span>").attr({"class":"detail-text"}));var e=d.clone(),f=d.clone(),d=d.clone(),g=
new Date;e.find("td:first span").text(a.localization.string("Date"));e.find("td:nth-child(2) span").text(g.toLocaleDateString());f.find("td:first span").text(a.localization.string("Time"));f.find("td:nth-child(2) span").text(g.toLocaleTimeString());if(g=CTXS.getCookie("NSC_ERRM"))formatError(g,!1),null==util.epaFailResult.epaMessage&&(util.epaFailResult.epaMessage=_localize("GenericError"));if(util.epaFailResult){var h=a("<ul></ul>");h.css("list-style-type","circle");h.css("margin","0.5em");var k=
d.find("td:nth-child(2) span");a.each(util.epaFailResult.epaErrors,function(b,c){h.append(a("<li></li>").text(c))});a.each(util.epaFailResult.epaMessage,function(b,c){epaMessageValue=a("<span><span/>");var d=c.split(":::")[1];"undefined"!==typeof d?""===d?epaMessageValue.text(_localize("epa_config_error_msg")):epaMessageValue.text(_localize("epa_error_msg")).append(d):epaMessageValue.text(c);k.append(epaMessageValue);k.append(a("</br>"))});k.append(h);k.append("<br/>");d.find("td:nth-child(2) span").append(k)}else g=
_localize("GenericError"),d.find("td:nth-child(2) span").text(g);d.find("td:first span").text(a.localization.string("EPAMessaage"));d.find("td:first").attr("style","vertical-align:top");c.append(e,f,d);b.append(c);b.append("<br/>");c=a("<a></a>").attr({"class":"button forms-authentication-button default",href:"#"}).text(a.localization.string("TryAgain"));b.append(c);UnsetCookie("NSC_ERRM");b.ctxsLocalize();return b},parseAsType:function(){return"plain"}})}})})(jQuery);
var epa_form,success_callback_global,autoposted=0,isFirstEpaScan=1;function epa_success_callback(a){util.clearAllTimeouts();resetGlobalVars();0==autoposted&&(autoposted=1,success_callback_global(a));1==isFirstEpaScan&&(isFirstEpaScan=0)}
var util={win:{},linux:{},mac:{},timers:[],emptyFunction:function(){},ajaxGet:function(a,b,c){c="undefined"!==typeof c?c:util.emptyFunction;try{var d=new XMLHttpRequest;d.open("GET",a);d.onerror=c;d.onreadystatechange=function(){4==d.readyState&&b(d)};d.send()}catch(e){c("Error in sending request"+e)}},synAjax:function(a,b){try{var c=new XMLHttpRequest;c.open(a,b,!1);c.send();return c}catch(d){}},parseToXml:function(a){var b;window.DOMParser?b=(new DOMParser).parseFromString(a,"text/xml"):(b=new ActiveXObject("Microsoft.XMLDOM"),
b.async=!1,b.loadXML(a));return b},extractPluginInfo:function(a,b,c){for(var d=0;d<a.childNodes.length;d++)if("repository"===a.childNodes[d].nodeName&&a.childNodes[d].getAttribute("name")===b)for(var e=a.childNodes[d],f=0;f<e.childNodes.length;f++)if("plugin"===e.childNodes[f].nodeName&&e.childNodes[f].getAttribute("type")===c)return{path:e.childNodes[f].getAttribute("path"),version:e.childNodes[f].getAttribute("version"),compatibleFrom:e.childNodes[f].getAttribute("compatibleFrom"),compatibleTill:e.childNodes[f].getAttribute("compatibleTill")};
return null},extractPluginHeader:function(a,b,c){b=c.toLowerCase()+"_"+b.toLowerCase();a=a.split(";");for(c=0;c<a.length;c++){var d=a[c].split(":");if(d[0]==b)return d[1]}return"Always"},getPluginInfo:function(a,b,c){var d=util.synAjax("GET","/vpn/pluginlist.xml"),e=util.parseToXml(d.responseText).firstChild,f=d.getResponseHeader("repository"),d=util.extractPluginHeader(d.getResponseHeader("Plugin-Upgrade"),a,b);a=a+"-"+("undefined"!==typeof c?c:b);if(null!==f&&""!=f&&(f=util.extractPluginInfo(e,
f,a))&&f.path&&f.version&&f.compatibleFrom)return f.upgradeType=d,f;f=util.extractPluginInfo(e,"default",a);f.upgradeType=d;return f},redirectToPlugin:function(a,b){var c=util.getPluginInfo(a,b);window.location.assign(c.path)},compareVersion:function(a,b){for(var c=a.split(/[\.,]/),d=b.split(/[\.,]/),e=0;4>e;e++){var f=parseInt(c[e])-parseInt(d[e]);if(0!==f)return f}return 0}};util.win.ACTIVEX_SUPPORTED="ActiveXObject"in window;util.win.NOPSuccess=!1;var winAgentPortForLauncher=3198;
util.prob=function(a,b,c){image=new Image;image.onload=b;image.onerror=c;image.src="http://localhost:"+winAgentPortForLauncher+"/"+a+"&"+Math.random()};
util.getStringFromLauncher=function(a,b){var c=0,d=[],e=function(){b("")},f=function(){d.push(this.height-1);if(2<d.length&&0==d.length%2&&0==d[d.length-1]&&0==d[d.length-2])try{for(var g="",h=0;h<d.length-2;h+=2)var k=16*d[h]+d[h+1],g=g+("%"+(16>k?"0":"")+k.toString(16));b(decodeURIComponent(g))}catch(l){b("")}else c+=1,util.prob(a+"&"+c,f,e)};util.prob(a+"&"+c,f,e)};util.maxAttempt=20;util.currentAttempt=0;util.maxInactiveAttempts=12;util.useOnlyLocalHostComm=!1;util.useOnlyNSproxyComm=!0;
util.fallbackStarted=!1;util.isPluginActive=!1;util._launchErrorHandler=util.emptyFunction;util._launchSuccessHandler=util.emptyFunction;util.checkIfLaunched=util._checkIfLaunched;util._checkIfLaunched=function(){function a(){util.timers.push(window.setTimeout(function(){util._checkIfLaunched()},1E3))}util.fallbackStarted=!0;util.currentAttempt+=1;util.currentAttempt>util.maxAttempt?util._launchErrorHandler():util.prob("NOP",util._launchSuccessHandler,a)};
util.launchPlugin=function(a,b,c,d){var e="citrixNG://";c&&!util.useOnlyLocalHostComm&&(e=("EPA"==d?e+"epaplugin/":e+"vpnplugin/")+document.location.host,e+="/",e+=c,e+="/");-1!=navigator.userAgent.search("Firefox")?((c=document.getElementById("launcherIframe"))&&c.parentNode.removeChild(c),c=document.createElement("iframe"),c.setAttribute("src",e),c.id="launcherIframe",c.style.width="1px",c.style.height="1px",c.style.visibility="hidden",document.body.appendChild(c)):window.location=e;util._launchErrorHandler=
b;util._launchSuccessHandler=a;util.timers.push(window.setTimeout(function(){util.checkIfLaunched()},2E3))};util.useLauncher=!0;util.winMaxTimerValue=14;var EPAData={};
util.fillEPAData=function(){EPAData={};isEpaFactor?(console.log("NSC_TMAS Cookie. EPA as a Factor"),EPAData.type="PreAuth",EPAData.cookieName="NSC_TMAS",EPAData.pathName="/epa/epa.html"):ns_getcookie("NSC_EPAC")?(EPAData.type="PreAuth",EPAData.cookieName="NSC_EPAC",EPAData.pathName="/epa/epa.html"):ns_getcookie("NSC_AAAC")?(EPAData.type="PostAuth",EPAData.cookieName="NSC_AAAC",EPAData.pathName="/vpns/postepa.html"):(console.log("Error! no EPAC or AAAC cookie!"),window.location.reload());EPAData.url=
document.location.origin+EPAData.pathName;-1!=navigator.userAgent.indexOf("Linux")?(EPAData.OS="Linux",EPAData.launch=linux_launchEpaApp):-1==navigator.userAgent.indexOf("Windows NT")?-1==navigator.userAgent.indexOf("Mac OS X")?displayBrowserTypeError():(EPAData.OS="Mac",EPAData.launch=agmac_launchEpaApp):(EPAData.OS="Win",EPAData.is64bit=detectPluginBitness(),util.win.ACTIVEX_SUPPORTED&&!util.fallbackStarted?EPAData.launch=detectActiveX:util.useLauncher?EPAData.launch=detectPluginChrome:-1<navigator.userAgent.indexOf("Firefox")||
-1<navigator.userAgent.indexOf("Gecko/2")||-1<navigator.userAgent.indexOf("AppleWebKit")?EPAData.launch=detectPlugin:displayBrowserTypeError())};util.setTimeout=function(a,b){var c=window.setTimeout(a,b);util.timers.push(c);return c};util.clearAllTimeouts=function(){for(var a=0;a<util.timers.length;a++)window.clearTimeout(util.timers[a]);util.timers=[]};util.displayBrowserTypeError=function(){};
var nsversion="11,1,14,2",epaActiveX,epaPlugin,timerID=0,require64bitPlugin=!1,winPluginPath,isEpaFactor=!1,secureToken="",NS_OLD_COOKIE_LEN=32,nstrace="DEBUG";
function resetGlobalVars(){EPAData={};nstrace="DEBUG";isEpaFactor=!1;null!=epaActiveX&&(delete epaActiveX,epaActiveX=null,setTimeout(CollectGarbage,1));epaPlugin=null;timerID=0;supports65BytesCookie=require64bitPlugin=!1;winPluginPath=null;probErrors=bIsUserAdmin=0;maxProberrors=5;curTimerValue=util.winMaxTimerValue;agmac_nConnectAttempts=15;agmac_count=0;agmac_totalAttempts=80;agmac_domainName_ws="localhost";agmac_portNo=6256;agmac_isAppInstalled=agmac_isVersionMatch=1;agmac_epa_iframe=null;agmac_didShowDwnld=
0;agmac_timeInterval=1E3;agmac_nSecs=20;covpCookie="";covpCount=0;linux_cookie=agmac_EpaMsg="";linux_nConnectAttempts=15;linux_count=0;linux_totalAttempts=80;linux_domainName_ws="localhost";linux_startportNo=3118;linux_portNo=0;linux_isAppInstalled=linux_isVersionMatch=1;linux_epa_iframe=null;linux_didShowDwnld=0;linux_timeInterval=1E3;linux_nSecs=20;ff_count=Math.floor(100*Math.random());util.maxAttempt=20;util.currentAttempt=0;util.isPluginActive=!1;util.fallbackStarted=!1;secureToken="";util.winMaxTimerValue=
20;util.maxInactiveAttempts=12;util.win.NOPSuccess=!1}function getNSVip(){return"NSC_TMAS"==EPAData.cookieName?(console.log("EPA as a Factor. Sending new VIP"),"255.255.255.254"):"255.255.255.255"}function UnsetCookie(a){document.cookie=a+"=nothing;expires=Thursday, 1 Jan 1970 00:00:00 GMT; path=/"}function displayBrowserTypeError(){}function SetErrMsg(a){var b=new Date;b.setTime((new Date).getTime()+864E5);document.cookie="NSC_ERRM="+encodeURIComponent(a)+";path=/;expires="+b.toGMTString()}
var bIsUserAdmin=0;function setVersionVars(a){0<util.compareVersion(a,"12,0,0,0")&&(supports65BytesCookie=!0)}
function isUpgradeRequired(a){setVersionVars(a);if(0==util.compareVersion(a,"1,1,1,1"))return!1;if(0>util.compareVersion(a,"11,0,0,0"))return!0;var b=util.getPluginInfo("WIN","EPA",use64BitEPA()?"EPA64":"EPA");return"Never"==b.upgradeType?!1:"Essential"==b.upgradeType?b.compatibleTill&&""!==b.compatibleTill&&0<util.compareVersion(a,b.compatibleTill)?!0:0>util.compareVersion(a,b.compatibleFrom):0!=util.compareVersion(b.version,a)}
function versionMismatchFallbackNonIE(){try{var a=0;bIsUserAdmin||(a=epaPlugin.isUserActionRequired(nsversion));"1"==a?timerID&&window.clearTimeout(timerID):("-1"==a&&(document.cookie="EPA_ADMIN_USER=1; path=/"),document.cookie="EPA_VERMISMATCH=1; path=/",detectEpaComponent(!0))}catch(b){document.cookie="EPA_VERMISMATCH=1; path=/",detectEpaComponent(!0)}}
function versionMismatchFallback(){try{var a=0;bIsUserAdmin||(a=epaActiveX.isUserActionRequired(nsversion));"1"==a?(timerID&&window.clearTimeout(timerID),document.getElementById("download_epa_content").style.display="none"):("-1"==a&&(document.cookie="EPA_ADMIN_USER=1; path=/"),document.cookie="EPA_VERMISMATCH=1; path=/",detectEpaComponent(!0))}catch(b){document.cookie="EPA_VERMISMATCH=1; path=/",detectEpaComponent(!0)}}
function launchEPAPluginNonIE(a){UnsetCookie("EPA_VERMISMATCH");UnsetCookie("EPA_ADMIN_USER");clearInterval(util.pollNSId);secureToken&&""==ns_getcookie(EPAData.cookieName)?util.getNoHttpOnlyCookies(function(){util.fillEPAData();epaPlugin.StartEpa(ns_getcookie(EPAData.cookieName),EPAData.url,nstrace,getNSVip(),a,navigator.userAgent+", "+navigator.platform,document.title);timerID=window.setTimeout(function(){probeEPAResultPlugin()},1E3);util.timers.push(timerID)}):(epaPlugin.StartEpa(ns_getcookie(EPAData.cookieName),
EPAData.url,nstrace,getNSVip(),a,navigator.userAgent+", "+navigator.platform,document.title),timerID=window.setTimeout(function(){probeEPAResultPlugin()},1E3),util.timers.push(timerID))}
function launchEPAPlugin(a){UnsetCookie("EPA_VERMISMATCH");UnsetCookie("EPA_ADMIN_USER");document.getElementById("skipbutton").style.display="none";clearInterval(util.pollNSId);secureToken&&""==ns_getcookie(EPAData.cookieName)?util.getNoHttpOnlyCookies(function(){util.fillEPAData();epaActiveX.StartEpa(ns_getcookie(EPAData.cookieName),EPAData.url,nstrace,getNSVip(),a,navigator.userAgent+", "+navigator.platform,document.title);timerID=window.setTimeout(function(){probeEPAResultPlugin()},1E3);util.timers.push(timerID)}):
(epaActiveX.StartEpa(ns_getcookie(EPAData.cookieName),EPAData.url,nstrace,getNSVip(),a,navigator.userAgent+", "+navigator.platform,document.title),timerID=window.setTimeout(function(){probeEPAResult()},1E3),util.timers.push(timerID))}
function detectActiveX(){timerID&&window.clearTimeout(timerID);try{if(1==ns_getcookie("EPA_VERMISMATCH")){1==ns_getcookie("EPA_ADMIN_USER")&&(bIsUserAdmin=1);AppendDownloadButton();UnsetCookie("EPA_VERMISMATCH");util.timers.push(window.setTimeout(function(){detectActiveX()},12E3));return}epaActiveX=new ActiveXObject("nsepacom.nsepaclass");var a=epaActiveX.getEPAVersion();isUpgradeRequired(a)?(epaActiveX=null,setTimeout(CollectGarbage,10),versionMismatchFallback()):launchEPAPlugin(a);return}catch(b){}document.getElementById("downloadbutton")||
(console.log("Appending download button"),AppendDownloadButton());util.timers.push(window.setTimeout(function(){detectActiveX()},1E3))}
function probeEPAResult(a){isInsideVPN()?(EPAData.type="PreAuth",msg=a):msg=epaActiveX.getEPAResult();"wait"==msg?(timerID=window.setTimeout(function(){probeEPAResult()},1E3),util.timers.push(timerID)):"passed"==msg&&"PreAuth"===EPAData.type?(console.log("EPA Passed"),epa_success_callback("passed")):"choices"==msg||"passed"==msg?(a=epaActiveX.getEPAErrcookie(),null!=a&&(document.cookie="NSC_VPNERR="+a),epa_success_callback(msg)):-1!=msg.search(/<link>/i)&&-1!=msg.search(/<\/link>/i)?(a=msg.search(/<link>/i)+
6,window.location.href=msg.slice(a,msg.search(/<\/link>/i))):(SetErrMsg(msg),epa_success_callback("failure"))}
function versionMismatchFallbackChrome(){function a(){document.cookie="EPA_VERMISMATCH=1; path=/";detectEpaComponent(!0)}function b(){var a=this.height;1==a?(timerID&&window.clearTimeout(timerID),document.getElementById("download_epa_content").style.display="none"):(2==a&&(document.cookie="EPA_ADMIN_USER=1; path=/"),document.cookie="EPA_VERMISMATCH=1; path=/",detectEpaComponent(!0))}AppendDownloadButton();bIsUserAdmin?a():util.prob("isUserActionRequired&"+nsversion,b,a)}
var probErrors=0,maxProberrors=5;
function probeEPAResultChrome(){function a(a){""==a?probeEPAResultChrome():(document.cookie="NSC_VPNERR="+a,a=function(){return afterEPAExit("passed")},util.prob("exit",a,a))}util.getStringFromLauncher("getEPAResult",function(b){document.getElementById("PluginCheck").style.display="none";document.getElementById("timer").style.display="none";""==b?probErrors<maxProberrors?(probErrors++,util.timers.push(window.setTimeout(function(){probeEPAResultChrome()},1E3))):(probErrors=0,detectEpaComponent()):
"wait"==b?(timerID=window.setTimeout(function(){probeEPAResultChrome()},1E3),util.timers.push(timerID)):"passed"==b&&"PreAuth"===EPAData.type?(b=function(){return afterEPAExit("passed")},util.prob("exit",b,b)):"choices"==b||"passed"==b?(EPAErrcookieMsg=b,util.getStringFromLauncher("getEPAErrcookie",a)):(showEpaError(b),b=function(){return afterEPAExit("failure")},util.prob("exit",b,b))})}
function showEpaError(a){if(-1!=a.search(/<link>/i)&&-1!=a.search(/<\/link>/i)){var b=a.search(/<link>/i)+6;window.location.href=a.slice(b,a.search(/<\/link>/i))}else SetErrMsg(a)}
function launchEPAPluginChrome(a){function b(){console.log("Error launching EPA plugin for Chrome")}UnsetCookie("EPA_VERMISMATCH");UnsetCookie("EPA_ADMIN_USER");util.prob("StartEpa&"+encodeURIComponent(ns_getcookie(EPAData.cookieName)+"&"+EPAData.url+"&"+nstrace+"&"+getNSVip()+"&"+a+"&"+navigator.userAgent+", "+navigator.platform+"&"+document.title),function(){2==this.height?(document.getElementById("skipbutton").style.display="none",util.timers.push(window.setTimeout(function(){probeEPAResultChrome()},
3E3))):b()},b)}function onChromeVersion(a){""==a?util.timers.push(window.setTimeout(function(){detectPluginChrome()},2E3)):isUpgradeRequired(a)?versionMismatchFallbackChrome():launchEPAPluginChrome(a)}var curTimerValue=util.winMaxTimerValue,showTimerHandler;
function showTimerDisplay(a){a?(document.getElementById("PluginCheck").style.display="",document.getElementById("timer").style.display=""):(AppendDownloadButton(),document.getElementById("PluginCheck").style.display="none",document.getElementById("timer").style.display="none")}function noLauncher(){showTimerDisplay(!1);curTimerValue=util.winMaxTimerValue;util.timers.push(window.setTimeout(function(){probEPAPlugin()},1E4))}
function showTimer(){0==curTimerValue?noLauncher():(showTimerDisplay(!0),document.getElementById("timer").innerHTML=curTimerValue+" "+_localize("secs"),--curTimerValue,showTimerHandler=window.setTimeout(function(){showTimer()},1E3),util.timers.push(showTimerHandler))}function stopTimer(){"undefined"!=typeof showTimerHandler&&(document.getElementById("PluginCheck").style.display="none",document.getElementById("timer").style.display="none",clearTimeout(showTimerHandler))}
function launcherExist(){clearInterval(util.pollNSId);util.win.NOPSuccess=!0;secureToken&&!ns_getcookie(EPAData.cookieName)?util.getNoHttpOnlyCookies(function(){util.fillEPAData();util.getStringFromLauncher("getEPAVersion",onChromeVersion)}):util.getStringFromLauncher("getEPAVersion",onChromeVersion);stopTimer();document.getElementById("skipbutton").style.display="none"}var probFailCount=0;
function onProbFailure(){25>probFailCount&&(util.timers.push(window.setTimeout(function(){probEPAPlugin()},2E3)),probFailCount++)}function probEPAPlugin(){util.useOnlyNSproxyComm||util.prob("NOP",launcherExist,onProbFailure)}
function detectPluginChrome(a){document.getElementById("PluginCheck").style.display="none";document.getElementById("timer").style.display="none";1==ns_getcookie("EPA_ADMIN_USER")&&(bIsUserAdmin=1);1==ns_getcookie("EPA_VERMISMATCH")?util.prob("exit",afterEPADownload,afterEPADownload):"already launched"===a?(util.checkIfLaunched=util._checkIfLaunched,util._launchSuccessHandler=launcherExist,util.checkIfLaunched()):(util.launchPlugin(launcherExist,function(){},secureToken,!0),showTimer())}
function afterEPADownload(){UnsetCookie("EPA_VERMISMATCH");util.timers.push(window.setTimeout(function(){probEPAPlugin()},1E4))}function afterEPAExit(a){epa_success_callback(a)}
function detectLinuxPlugin(){timerID&&window.clearTimeout(timerID);try{if(navigator.plugins.refresh(!1),navigator.mimeTypes["application/x-epa"]){document.getElementById("nsepadiv").innerHTML=require64bitPlugin?'<object id="npobj" type="application/citrix-npagee64" height="1" width="1"></OBJECT>':'<object id="npobj" type="application/x-epa" height="1" width="1"></OBJECT>';epaPlugin=document.getElementById("npobj");var a=document.location.host;"upgrade"==epaPlugin.checkEPAUpgrade(a)?(AppendDownloadButton(),
document.cookie="EPA_VERMISMATCH=1; path=/",util.timers.push(window.setTimeout(function(){detectLinuxPlugin()},1E3))):(UnsetCookie("EPA_VERMISMATCH"),UnsetCookie("EPA_ADMIN_USER"),document.getElementById("PluginCheck").style.display="none",a=document.location.protocol+"//"+document.location.host,clearInterval(util.pollNSId),secureToken&&""==ns_getcookie(EPAData.cookieName)?util.getNoHttpOnlyCookies(function(){util.fillEPAData();epaPlugin.StartEpa(getEPACookie(),a,EPAData.pathName);timerID=window.setTimeout(function(){probeEPAResultPlugin()},
1E3);util.timers.push(timerID)}):(epaPlugin.StartEpa(getEPACookie(),a,EPAData.pathName),timerID=window.setTimeout(function(){probeEPAResultPlugin()},1E3),util.timers.push(timerID)))}else document.getElementById("PluginCheck").style.display="none",AppendDownloadButton(),util.timers.push(window.setTimeout(function(){detectLinuxPlugin()},1E3))}catch(b){AppendDownloadButton(),util.timers.push(window.setTimeout(function(){detectLinuxPlugin()},1E3))}}
function detectPlugin(){timerID&&window.clearTimeout(timerID);try{if(1==ns_getcookie("EPA_VERMISMATCH")){1==ns_getcookie("EPA_ADMIN_USER")&&(bIsUserAdmin=1);document.getElementById("PluginCheck").style.display="none";AppendDownloadButton();UnsetCookie("EPA_VERMISMATCH");util.timers.push(window.setTimeout(function(){detectPlugin()},12E3));return}navigator.plugins.refresh(!1);if(require64bitPlugin?navigator.mimeTypes["application/citrix-npagee64"]:navigator.mimeTypes["application/citrix-npagee"]){document.getElementById("nsepadiv").innerHTML=
require64bitPlugin?'<object id="epaobj" type="application/citrix-npagee64" height="1" width="1"></OBJECT>':'<object id="epaobj" type="application/citrix-npagee" height="1" width="1"></OBJECT>';epaPlugin=document.getElementById("epaobj");var a=epaPlugin.getEPAVersion();isUpgradeRequired(a)?versionMismatchFallbackNonIE():(document.getElementById("download_epa_content").style.display="none",launchEPAPluginNonIE(a));return}}catch(b){}document.getElementById("PluginCheck").style.display="none";AppendDownloadButton();
util.timers.push(window.setTimeout(function(){detectPlugin()},1E3))}
function probeEPAResultPlugin(){try{msg=epaPlugin.getEPAResult()}catch(b){console.log("Error getting EPA result - "+b)}if("wait"==msg)timerID=window.setTimeout(function(){probeEPAResultPlugin()},1E3),util.timers.push(timerID);else if("passed"==msg&&"PreAuth"===EPAData.type)epa_success_callback("passed");else if("choices"==msg||"passed"==msg){var a=epaPlugin.getEPAErrcookie();null!=a&&(document.cookie="NSC_VPNERR="+a);epa_success_callback("passed")}else SetErrMsg(msg),epa_success_callback("failed")}
var agmac_cookie,agmac_nConnectAttempts=15,agmac_count=0,agmac_totalAttempts=80,agmac_domainName_ws="localhost",agmac_portNo=6256,agmac_isVersionMatch=1,agmac_isAppInstalled=1,agmac_epa_iframe,agmac_didShowDwnld=0,agmac_timeInterval=1E3,agmac_nSecs=20,covpCookie="",covpCount=0,agmac_EpaMsg="";
function agmac_showTimer(){0<agmac_nSecs?(document.getElementById("timer").innerHTML=agmac_nSecs+" "+_localize("secs"),util.timers.push(window.setTimeout(function(){agmac_showTimer()},agmac_timeInterval)),--agmac_nSecs):util.useOnlyNSproxyComm&&!util.isPluginActive&&agmac_showDownload(_localize("epa_launch_failure_msg"))}
function agmac_launchEpaApp(a,b){var c="com.citrix.agmacepa://";"launch"===a&&(b&&!util.useOnlyLocalHostComm&&(c=c+"epaplugin/"+document.location.host,c+="/",c+=b,c+="/"),document.getElementById("PluginCheck").innerHTML=_localize("Checking_if_the_plug-in_is_installed"),agmac_showTimer(),-1<navigator.userAgent.indexOf("Chrome")&&"Google Inc."==navigator.vendor?window.location=c:(agmac_epa_iframe=document.createElement("iframe"),document.body.appendChild(agmac_epa_iframe),agmac_epa_iframe.setAttribute("width",
"1"),agmac_epa_iframe.setAttribute("height","1"),agmac_epa_iframe.hidden=!0,agmac_epa_iframe.src=c));a&&!b&&util.timers.push(window.setTimeout(function(){agmac_startChannel()},2500))}
function agmac_startChannel(){if(agmac_count<agmac_nConnectAttempts){agmac_cookie=getEPACookie();var a=new Image;a.onload=agmac_sepaHandler;a.onerror=agmac_sepaError;a.src="http://localhost:"+agmac_portNo+"/sepa?"+agmac_cookie+"?"+window.location.host+"?"+EPAData.type.toUpperCase()}else agmac_showDownload(_localize("epa_launch_failure_msg"))}
function agmac_sepaError(){console.log("error : "+agmac_count);agmac_count++;agmac_portNo++;6260<agmac_portNo&&(agmac_portNo=6256);util.timers.push(window.setTimeout(function(){agmac_startChannel()},1E3))}function agmac_sepaHandler(a){document.getElementById("timer").style.display="none";console.log("img height: "+this.height);2==this.height?(document.getElementById("skipbutton").style.display="none",agmac_sendrepa()):(SetErrMsg(_localize("EPA_failure_msg")),epa_success_callback("failed"))}
var ff_count=Math.floor(100*Math.random());function agmac_sendrepa(){var a=new Image;a.onload=agmac_repaHandler;a.onerror=agmac_repaError;a.src="http://localhost:"+agmac_portNo+"/repa?"+agmac_cookie+"?"+ff_count}
function agmac_repaHandler(){1==this.height?(ff_count+=1,util.timers.push(window.setTimeout(function(){agmac_sendrepa()},3E3))):2==this.height?(console.log("upgrade EPA"),agmac_showDownload(_localize("epa_download_msg")),util.timers.push(window.setTimeout(function(){agmac_startChannel()},1E3))):3==this.height?agmac_sendEpaMsg():4==this.height&&("PostAuth"===EPAData.type?agmac_sendcovp():epa_success_callback("passed"))}function agmac_repaError(){agmac_epafailed()}
function agmac_sendEpaMsg(){console.log("agmac_sendEpaMsg");var a=new Image;a.onload=agmac_EpaMsgHandler;a.onerror=agmac_EpaMsgError;a.src="http://localhost:"+agmac_portNo+"/epamsg?"+agmac_cookie+"?"+agmac_EpaMsg.length+"?"+ff_count}
function agmac_EpaMsgHandler(){if(2!=this.height){agmac_EpaMsg+=String.fromCharCode(this.height);ff_count+=1;var a=new Image;a.onload=agmac_EpaMsgHandler;a.onerror=agmac_EpaMsgError;a.src="http://localhost:"+agmac_portNo+"/epamsg?"+agmac_cookie+"?"+agmac_EpaMsg.length+"?"+ff_count}else console.log("agmac_EpaMsg = ",agmac_EpaMsg),agmac_epafailed()}function agmac_EpaMsgError(){agmac_epafailed()}
function agmac_epafailed(){console.log("epa failed");""==agmac_EpaMsg?SetErrMsg(_localize("EPA_failure_msg")):SetErrMsg(agmac_EpaMsg);epa_success_callback("failed")}function agmac_sendcovp(){image=new Image;image.onerror=covpError;image.onload=covpSuccess;image.src="http://localhost:"+agmac_portNo+"/covp?"+agmac_cookie+"?"+covpCookie}function covpError(){SetErrMsg(_localize("EPA_failure_msg"));epa_success_callback("failed")}
function covpSuccess(a){1==this.height?(covpCookie="NSC_VPNERR="+covpCount+covpCookie,console.log("We done ="+covpCookie),document.cookie=covpCookie,epa_success_callback("passed")):(2==this.height&&(covpCount+=1,covpCookie+=",wicps"),3==this.height&&(covpCount+=1,covpCookie+=",cvpn"),4==this.height&&(covpCount+=1,covpCookie+=",java"),5==this.height&&(covpCount+=1,covpCookie+=",mac"),6==this.height&&(covpCount+=1,covpCookie+=",agent"),util.timers.push(window.setTimeout(function(){agmac_sendcovp()},
1E3)))}function agmac_showDownload(a){agmac_didShowDwnld||(agmac_didShowDwnld=1,document.getElementById("timer").style.display="none",document.getElementById("PluginCheck").innerHTML=a,document.getElementById("PluginCheck").style.display="",AppendDownloadButton(),agmac_nConnectAttempts=agmac_totalAttempts,agmac_count=0,util.useOnlyNSproxyComm||agmac_startChannel())}
function AppendDownloadButton(){if(isFirstEpaScan){var a=document.getElementById("retry_epa_launch_content");a&&(a.style.display="none");a=document.getElementById("download_epa_content");if(a)"none"==a.style.display&&(a.style.display="");else{var a=$("<p></p>").attr({"class":"detail-text"}).text(_localize("epa_undetected_msg")),b=$("<a></a>").attr({id:"downloadbutton","class":"default button",style:"cursor:pointer"}).text(_localize("Download"));$(b).click(function(a){onDownload()});a=$('<div"></div>').attr({"class":"",
id:"download_epa_content"}).append(a,b);$(epa_form).append(a)}}else{if(a=document.getElementById("download_epa_content"))a.style.display="none";AppnedEpaRetryLaunchButton()}}
function AppnedEpaRetryLaunchButton(){var a=document.getElementById("retry_epa_launch_content");if(a)"none"==a.style.display&&(a.style.display="");else{var a=$("<p></p>").attr({"class":"detail-text"}).text(_localize("epa_retry_launch_msg")),b=$("<a></a>").attr({id:"launchbutton","class":"default button",style:"cursor:pointer"}).text(_localize("RetryEpaLaunch"));$(b).click(function(a){util.clearAllTimeouts();isEpaFactor&&secureToken&&!util.useOnlyLocalHostComm?(clearInterval(util.pollNSId),"Win"===
EPAData.OS?util.win.pluginLaunch("EPA"):"Mac"===EPAData.OS?util.mac.pluginLaunch():"Linux"===EPAData.OS?util.linux.pluginLaunch("EPA"):console.log("invalid OS during retry; "+EPAData.OS)):"Linux"===EPAData.OS?EPAData.launch():EPAData.launch("launch")});a=$('<div"></div>').attr({"class":"",id:"retry_epa_launch_content"}).append(a,b);$(epa_form).append(a)}}
function detectEpaComponent(a){autoposted=0;isInsideVPN()?triggerEPA():(util.clearAllTimeouts(),util.fillEPAData(),isEpaFactor&&secureToken&&!util.useOnlyLocalHostComm&&!a?(util.fallbackStarted=!1,"Win"===EPAData.OS?util.win.pluginLaunch("EPA"):"Mac"===EPAData.OS?util.mac.pluginLaunch():"Linux"===EPAData.OS&&util.linux.pluginLaunch("EPA")):(secureToken&&util.getNoHttpOnlyCookies(),util.fillEPAData(),util.checkIfLaunched=util._checkIfLaunched,"Mac"===EPAData.OS&&"PostAuth"===EPAData.type?window.setTimeout(function(){EPAData.launch("launch")},
5E3):"Linux"===EPAData.OS?EPAData.launch():EPAData.launch("launch")))}var linux_cookie,linux_nConnectAttempts=15,linux_count=0,linux_totalAttempts=80,linux_domainName_ws="localhost",linux_startportNo=3118,linux_portNo,linux_isVersionMatch=1,linux_isAppInstalled=1,linux_epa_iframe,linux_didShowDwnld=0,linux_timeInterval=1E3,linux_nSecs=20,ff_count=Math.floor(100*Math.random());
function linux_showTimer(){0<linux_nSecs&&(document.getElementById("timer").innerHTML=linux_nSecs+" "+_localize("secs"),util.timers.push(window.setTimeout(function(){linux_showTimer()},linux_timeInterval)),--linux_nSecs)}
function linux_launchEpaApp(a){var b="nsgcepa://nsgcepa";a&&!util.useOnlyLocalHostComm&&(b=b+"/"+document.location.host,b+="/",b+=a,b+="/");document.getElementById("PluginCheck").innerHTML=_localize("Checking if the plug-in is installed");linux_showTimer();if(-1!=navigator.userAgent.search("Firefox")){var c=document.getElementById("launcherIframe");c&&c.parentNode.removeChild(c);c=document.createElement("iframe");c.setAttribute("src",b);c.id="launcherIframe";c.style.width="1px";c.style.height="1px";
c.style.visibility="hidden";document.body.appendChild(c)}else window.location=b;linux_portNo=linux_startportNo;a&&!util.useOnlyLocalHostComm&&util.pluginResults();util.useOnlyNSproxyComm||util.timers.push(window.setTimeout(function(){linux_startChannel()},2500))}
function linux_startChannel(){util.fallbackStarted=!0;console.log("linux_startChannel: "+linux_count+linux_portNo);if(linux_count<linux_nConnectAttempts){var a="";"NSC_TMAS"===EPAData.cookieName?(linux_cookie="NSC_EPAC="+ns_getcookie("NSC_TMAS"),a=getEPACookie()):linux_cookie=getEPACookie();var b=new Image;b.onload=linux_sepaHandler;b.onerror=linux_sepaError;b.src="http://localhost:"+linux_portNo+"/sepa?"+linux_cookie+"?nsloc=https://"+window.location.hostname+"?"+EPAData.type.toUpperCase()+"?"+a+
"?"+ff_count}else linux_showDownload(_localize("epa_launch_failure_msg"))}function linux_sepaError(){console.log("linux_sepaError: "+linux_count+linux_portNo);linux_count++;linux_portNo++;linux_portNo>linux_startportNo+5&&(linux_portNo=linux_startportNo);util.timers.push(window.setTimeout(function(){linux_startChannel()},1E3))}
function linux_sepaHandler(a){clearInterval(util.pollNSId);ns_getcookie(EPAData.cookieName)?(document.getElementById("timer").style.display="none",console.log("img height: "+this.height),2==this.height?(document.getElementById("skipbutton").style.display="none",linux_sendrepa()):(SetErrMsg(_localize("EPA_failure_msg")),epa_success_callback("failed"))):(util.getNoHttpOnlyCookies(),linux_sepaError())}
function linux_sendrepa(){console.log("sending repa");var a=new Image;a.onload=linux_repaHandler;a.onerror=linux_repaError;a.src="http://localhost:"+linux_portNo+"/repa?"+linux_cookie+"?"+ff_count;ff_count+=1}
function linux_repaHandler(){1==this.height?(console.log("height1"),ff_count+=1,util.timers.push(window.setTimeout(function(){linux_sendrepa()},2E3))):2==this.height?(console.log("upgrade EPA"),linux_showDownload(_localize("epa_download_msg"))):3==this.height?(console.log("EPA failed"),SetErrMsg(_localize("EPA_failure_msg")),epa_success_callback("failed")):4==this.height&&(console.log("EPA success"),"PostAuth"===EPAData.type?linux_sendcovp():epa_success_callback("passed"))}
function linux_repaError(){SetErrMsg(_localize("EPA_failure_msg"));epa_success_callback("failed")}function linux_sendcovp(){image=new Image;image.onerror=linux_covpError;image.onload=linux_covpSuccess;image.src="http://localhost:"+linux_portNo+"/covp?"+linux_cookie+"?covp="+covpCookie}function linux_covpError(){SetErrMsg(_("End point analysis failed"));document.cookie="NSC_AAAC=nothing;expires=Thursday, 1 Jan 1970 00:00:00 GMT; path=/";window.location="/epa/posterrorpage.html"}
function linux_covpSuccess(a){1==this.height?(covpCookie="NSC_VPNERR="+covpCount+covpCookie,console.log("We done ="+covpCookie),document.cookie=covpCookie,epa_success_callback("passed")):(2==this.height&&(covpCount+=1,covpCookie+=",wicps"),3==this.height&&(covpCount+=1,covpCookie+=",cvpn"),4==this.height&&(covpCount+=1,covpCookie+=",java"),5==this.height&&(covpCount+=1,covpCookie+=",mac"),6==this.height&&(covpCount+=1,covpCookie+=",agent"),util.setTimeout(linux_sendcovp,1E3))}
function linux_showDownload(a){linux_count=0;util.useOnlyNSproxyComm||linux_startChannel();linux_didShowDwnld||(linux_didShowDwnld=1,document.getElementById("timer").style.display="none",document.getElementById("PluginCheck").innerHTML=a,document.getElementById("PluginCheck").style.display="",AppendDownloadButton(),linux_nConnectAttempts=linux_totalAttempts)}
function downloadLinuxPlugin(){0<=navigator.platform.indexOf("i686")?window.location.assign("/epa/scripts/linux/nsepa32.deb"):window.location.assign("/epa/scripts/linux/nsepa.deb")}function onDownload(){0<=navigator.userAgent.indexOf("Linux")?downloadLinuxPlugin():-1!=navigator.userAgent.indexOf("Mac OS X")?window.location.assign("/epa/scripts/mac/Citrix_Endpoint_Analysis.dmg"):use64BitEPA()?util.redirectToPlugin("WIN","EPA64"):util.redirectToPlugin("WIN","EPA")}
function use64BitEPA(){return-1<navigator.userAgent.indexOf("Win64")||-1<navigator.userAgent.indexOf("WOW64")||require64bitPlugin}function detectPluginBitness(){(-1<navigator.userAgent.indexOf("Gecko/2")||-1<navigator.userAgent.indexOf("AppleWebKit"))&&"Win64"==navigator.platform&&(require64bitPlugin=!0)}function showDownloadPrompt(){}function _(a){return a}function getEPACookie(){return EPAData.cookieName+"="+ns_getcookie(EPAData.cookieName)}
function formatError(a,b){util.epaFailResult={};util.epaFailResult.epaMessage=[];util.epaFailResult.epaErrors=[];var c=a.split("\n");if(3>c.length)util.epaFailResult.epaMessage.push(a);else{for(var d=0;1<c[d].length;)util.epaFailResult.epaMessage.push(c[d]),d++;for(d+=1;d<c.length;d++)1<c[d].length&&util.epaFailResult.epaErrors.push(c[d])}}
function makeJSsafe(a){var b=[{original:/&/g,replacement:"&amp;"},{original:/</g,replacement:"&lt;"},{original:/>/g,replacement:"&gt;"},{original:/"/g,replacement:"&quot;"},{original:/'/g,replacement:"&apos;"}];for(i=0;i<b.length;i++)a=a.replace(b[i].original,b[i].replacement);return a}
util.probeNS=function(a,b,c,d){sCallback=b?b:util.emptyFunction;eCallback=c?c:util.emptyFunction;$.ajax({type:"GET",url:a,dataType:"/pluginResults"==a?"json":"text",beforeSend:function(a){$.each(d,function(b,c){a.setRequestHeader(b,c)})},success:function(a,b,c){sCallback(a,b,c)},error:function(a,b,c){"timeout"==b?console.log("request timed out possibly due to plugin trying to establish tunnel or browser timing out the request"):"parsererror"==b&&""!=a.responseText?window.location="/":eCallback(a.responseText,
b,a)}})};
util.pollNS=function(a,b,c,d){util.pollNSId=setInterval(function(){util.probeNS(b,c,d);util.currentAttempt+=1;-1==navigator.userAgent.indexOf("Windows NT")||util.isPluginActive||util.fallbackStarted||util.useOnlyNSproxyComm?util.currentAttempt>util.maxInactiveAttempts&&!util.isPluginActive&&!util.fallbackStarted&&!util.useOnlyNSproxyComm?(util.checkIfLaunched=util.emptyFunction,d()):util.useOnlyNSproxyComm&&-1!=navigator.userAgent.indexOf("Linux")&&(0==util.currentAttempt%30&&"EPA"!==util.linux.type&&linux_launchVpnApp(secureToken),
20==util.currentAttempt&&("EPA"===util.linux.type?linux_showDownload(_localize("epa_launch_failure_msg")):displayDownloadArea())):(util.checkIfLaunched=util.emptyFunction,util._launchSuccessHandler="EPA"==util.win.type?launcherExist:detectAgent,util._launchErrorHandler=util.emptyFunction,d())},1E3)};
util.win.pluginLaunch=function(a){util.isPluginActive=!1;util.checkIfLaunched=util.pluginResults;util.win.type=a;clearInterval(util.pollNSId);"EPA"==a?(util.fallback=util.checkOnLocalhostPort,showTimer()):(util.fallback=util._checkIfLaunched,util._launchSuccessHandler=localhostPluginLaunch,!util.fallbackStarted&&util.currentAttempt<util.maxInactiveAttempts?showWinVPNTimer():displayDownloadArea());util.fallbackStarted=!1;util.launchPlugin(util.emptyFunction,util.fallback,secureToken,a)};
util.linux.pluginLaunch=function(a){util.isPluginActive=!1;util.fallbackStarted=!1;util.linux.type=a;clearInterval(util.pollNSId);"EPA"==a?linux_launchEpaApp(secureToken):(linux_launchVpnApp(secureToken),util.fallback=util.checkOnLocalhostPort,util.pluginResults())};util.mac.pluginLaunch=function(){util.isPluginActive=!1;util.fallbackStarted=!1;clearInterval(util.pollNSId);util.checkIfLaunched=util.pluginResults;util.fallback=util.checkOnLocalhostPort;agmac_launchEpaApp("launch",secureToken);util.pluginResults()};
util.pluginResults=function(){util.currentAttempt=0;util.pollNS(util.maxInactiveAttempts,"/pluginResults",util.pluginResultsSuccessHandler,util.fallback)};
util.pluginResultsSuccessHandler=function(a,b,c){"Inactive"==a.type?console.log(a.type):"Active"==a.type?(util.fallbackStarted||(util.isPluginActive=!0),clearTimeout(showTimerHandler),console.log(a.type)):"Upgrade EPA"==a.type?(util.fallbackStarted||(util.isPluginActive=!0),console.log("Upgrade EPA received"),AppendDownloadButton()):"Upgrade VPN"==a.type?(util.fallbackStarted||(util.isPluginActive=!0),console.log("Upgrade VPN received"),displayDownloadArea()):"Passed"==a.type?(clearInterval(util.pollNSId),
util.fallbackStarted||(util.isPluginActive=!0),console.log("pluginResult is "+a.type),epa_success_callback("passed")):"Failed"==a.type?(clearInterval(util.pollNSId),util.fallbackStarted||(util.isPluginActive=!0),console.log("pluginResult is "+a.type),util.epaFailResult={},util.epaFailResult.epaMessage=a.epaMessage.split("\n"),util.epaFailResult.epaErrors=a.epaErrors.split("\n"),util.epaFailResult.epaErrors.pop(),UnsetCookie("NSC_ERRM"),epa_success_callback("failure")):"Established"==a.type?(clearInterval(util.pollNSId),
util.fallbackStarted||(util.isPluginActive=!0),clearTimeout(showTimerHandler),console.log("pluginResult is "+a.type),success_callback_fullvpn("Establishing_fullvpn_Windows")):"choices"==a.type?(clearInterval(util.pollNSId),util.fallbackStarted||(util.isPluginActive=!0),console.log("pluginResult is "+a.type),epa_success_callback("passed")):console.error("Unexpected response")};
util.checkOnLocalhostPort=function(){util.fallbackStarted=!0;util._launchSuccessHandler=launcherExist;util._launchErrorHandler=util.emptyFunction;"Mac"===EPAData.OS?(agmac_count=util.maxInactiveAttempts,util.getNoHttpOnlyCookies(),EPAData.launch("already launched")):-1!=navigator.userAgent.indexOf("Linux")?(probeErrors=util.maxInactiveAttempts,util.getNoHttpOnlyCookies(function(){checkForCookies();probeError_linux()})):EPAData.launch("already launched")};
util.getNoHttpOnlyCookies=function(a){util.probeNS("/getCookies",a,util.emptyFunction,{"X-Citrix-Secure-Token":secureToken})};
