//note: as string delimiters please use double quotes only
(function ($) {
    $.localization.addStringBundle("en", {
        About: "About",
        AcceptTermsMessage: "Please accept the terms of the licensing agreement before installing Citrix Receiver.",
        AccessGatewayChangePasswordWarning: "Logoff is required after a successful password change. You will need to log on again to use your apps.",
        ActivateCitrixPlugin: "Activate the Citrix plug-in",
        ActivateCitrixPluginBrowser: "Please activate the Citrix plug-in in the browser",
        ActivateReceiver: "Activate...",
        ActivateReceiverToolTip: "Activate Citrix Receiver on your desktop",
        Add: "Add",
        AddAll: "Add All",
        Added: "Added",
        AddedToFavorites: "Remove",
        AddFavoritesTitle: "Add Favorites",
        AddFavoritesDescription: "Go to Desktops or Apps, click on Details next to your choice and then select Add to Favorites.",
        AddFavoritesDescriptionDesktopsOnly: "Go to Desktops, click on Details next to your choice and then select Add to Favorites.",
        AddFavoritesDescriptionAppsOnly: "Go to Apps, click on Details next to your choice and then select Add to Favorites.",
        AddFavoritesDescriptionPhone: "Under the menu, go to Desktops or Apps, click on Details next to your choice and then select Add to Favorites.",
        AddFavoritesDescriptionPhoneDesktopsOnly: "Under the menu, go to Desktops, click on Details next to your choice and then select Add to Favorites.",
        AddFavoritesDescriptionPhoneAppsOnly: "Under the menu, go to Apps, click on Details next to your choice and then select Add to Favorites.",
        AddToFavorites: "Add To Favorites",
        AllApps: "Apps",
        AllAppsTitle: "All Apps",
        AllAppsForToolbar: "All",
        AllowPluginToRun: "Allow this website to run the Citrix plug-in to access apps.",
        AllRightsReserved: "All rights reserved.",
        AlreadyInstalled: "Already installed",
        AppDetailsUnavailable: "App details unavailable",
        AppInMaintenance: "\"{0}\" is temporarily unavailable due to planned maintenance.",
        ApplicationLaunchPlugin: "Citrix plug-in for application launch.",
        AppRequestPendingApprovalCannotStart: "\"{0}\" is pending approval and cannot be started.",
        Approved: "Approved",
        AppStore: "Citrix Receiver",
        AuthFailureSmartcard: "You cannot log on using a smart card.",
        AuthFailureGeneric: "You cannot log on at this time.",
        AuthFailurePassthrough: "Cannot log on using the account you used to sign on to the computer.",
        Available: "Available",

        Back: "Back",
        BackToAppsAndDesktops: "Back to Apps and Desktops",
        BlankFolder: "[blank category]",
        Bundles: "Featured App Groups",

        Cancel: "Cancel",
        CancelRequest: "Cancel Request",
        CannotAddApp: "Cannot add app \"{0}\".",
        CannotAddAppTitle: "Cannot Add App",
        CannotCompleteYourRequest: "Cannot complete your request.",
        CannotDetectReceiverInstallAvailable: "We couldn't detect Citrix Receiver. Do you want to download and install it?",
        CannotGetYourAppsFromStore: "Cannot get your apps from the store.",
        CannotRemoveApp: "Cannot remove app \"{0}\".",
        CannotRemoveAppTitle: "Cannot Remove App",
        CannotMoveApp: "Cannot rearrange apps, as the server is currently unavailable.",
        CannotStartApp: "Cannot start app \"{0}\".",
        CannotStartDesktop: "Cannot start desktop \"{0}\".",
        CannotStartDesktopSuggestRestart: "Cannot start desktop \"{0}\". Try restarting it.",
        Categories: "Categories",
        ChangeClient: "Change Citrix Receiver...",
        ChangePassword: "Change password...",
        Check: "Check",
        CheckingForUpgrade: "We're checking now for an upgrade.",
        CheckForUpgrade: "Would you like to check for an upgrade for Citrix Receiver?",
        ChromeAppOriginMismatch: "Please contact your IT department with this information: You must whitelist the ID of Citrix Receiver in StoreFront.",
        ChromePluginHelperMessage: "Please allow the Citrix plug-in to run on this website to access apps. For more information refer to the Citrix Knowledge Center article {0}.",
        CitrixCopyright: "\u00a9 2016 Citrix Systems, Inc.",
        CitrixLicenseAgreement: "Citrix license agreement",
        ClearSearch: "Clear Search",
        ClickContinue: "click <strong>Continue</strong>.",
        ClickInstall: "Install Citrix Receiver to access your applications",
        ClickUpgrade: "Click install to upgrade Citrix Receiver",
        Close: "Close",
        CloseYourBrowserToEndSession: "Please close your browser to log off.",
        CloseYourBrowserToProtectAccount: "Please close your browser to protect your account.",
        ConfirmInstallationIsComplete: "Confirm installation is complete",
        Connect: "Connect",
        Continue: "Continue",
        CookiesAreDisabledBody: "Please enable cookies in your browser before using this version of Citrix Receiver",
        CookiesAreDisabledTitle: "Cookies Disabled",

        Denied: "Denied",
        DesktopInMaintenance: "The desktop \"{0}\" is temporarily unavailable due to planned maintenance.",
        DesktopRestartWarningText: "Restarting your desktop may solve the problem, but you will lose any unsaved work.",
        DesktopRestartWarningTitle: "Do you want to restart desktop \"{0}\"?",
        Desktops: "Desktops",
        DetectAgain: "Detect again",
        Details: "Details",
        DetectClient: "Detect client...",
        DetectReceiver: "Detect Receiver",
        Disconnect: "Disconnect",
        DisplayInFramesNotAllowed: "This site has been loaded within another web page. This page will be refreshed to reload the site.",
        DoYouWantToStartApp: "Do you want to start \"{0}\"?",
        Download: "Download",
        DownloadAgain: "Download again",
        DownloadReceiver: "Download Citrix Receiver...",
        DownloadingReceiver: "Downloading Citrix Receiver...",

        Faq: "FAQ",
        Featured: "Featured",
        Folders: "Folders",
        ForFullExperience: "For the best experience, use the full set of features bundled with {0}. Click Detect Receiver to get started.",

        GoBackToChoices: "Go back to choices",

        Help: "Help",

        IAgreeWith: "I agree with the",
        IfAlreadyInstalled: "If Citrix Receiver is detected, you will see a window in a few seconds. Please choose {0}.",
        IfNoWindowAlreadyInstalled: "If no window appears, select {0}.",
        IfNoWindowDetectAgain: "If no window appears, click {0}.",
        IfNoWindowOptions: "If no window appears, select from the options below.",
        IfWasInstalled: "If Citrix Receiver was installed successfully, your browser will show a window in a few seconds. Please choose {0}.",
        InfoBarSecurityInformation: "Allowing the ActiveX control to run will install software on your computer.",
        InProgress: "In Progress",
        Install: "Install",
        InstallationBegins: "Please wait while the download process begins.",
        InstallReceiver: "Install Citrix Receiver...",
        InstallWhenDownloadComplete: "Install Citrix Receiver on your machine when the download is complete. Once you've installed Citrix Receiver, return here and click {0}.",

        JustAMomentDetecting: "Just a moment, we're detecting if Citrix Receiver is already installed.",

        LaunchApplication: "Launch Application",
        Less: "Less",
        LicenseAgreementContentCode: "CTX_code EP_T_A124358",
        LicenseAgreementContentText: "Use of this component is subject to the Citrix license or terms of service covering the Citrix product(s) or service(s) with which you will be using this component. This component is licensed for use only with such Citrix product(s) or service(s).",
        LicenseAgreementContentTitle: "CITRIX(R) LICENSE AGREEMENT",
        LoadingContent: "Loading Content...",
        LoggingOff: "Logging off...",
        LoginTimedOut: "Logon has timed out due to inactivity.",
        LogOff: "Log Off",
        LogoffError: "Logoff error",
        LogOffSessionsFailed: "If any apps are still running, please exit them manually.",
        LogOn: "Log On",
        LogonHasExpired: "Your logon has expired. Please log on again to continue.",
        LogonTextPassthrough: "To use the account you used to sign on to the computer, click Log On.",
        LogonTextSmartcard: "Insert your smart card into the reader and click Log On.",

        ManageSecurityQuestions: "Manage Security Questions",
        Menu: "Menu",
        More: "More",
        MultiApprovedApps: "Your request to add these apps is approved.",
        MultiDeniedApps: "Your request to add these apps is denied.",

        NoAppsFound: "No items match your search.",
        NoAvailableAuthMethods: "No logon methods are available on this platform.",
        NoUpdates: "No Updates Available",
        NoUpgradesAvailable: "No upgrades for Citrix Receiver are available.",
        NoWindowDownload: "If no window appears, proceed to download.",

        OK: "OK",
        OnceComplete: "After Citrix Receiver is installed, ",
        Open: "Open",
        Other: "Other",
        Overview: "Overview",

        PartialRefreshFailure: "Some servers failed to respond",
        PasswordExpiresTodayMessage: "Your password will expire today.",
        PasswordExpiresTomorrowMessage: "Your password will expire in 1 day.",
        PasswordExpiryChange: "Change Now",
        PasswordExpiryChangeLater: "Not Now",
        PasswordExpiryMessage: "Your password will expire in {0} days.",
        PasswordExpiryTitle: "Do you want to change your password?",
        Pending: "Pending",
        PendingApproval: "Pending Approval",
        PhoneOrTabletRequired: "Phone or tablet required",
        PhoneOrTabletRequiredMessage: "Please use an iPhone, iPad, or Android phone or tablet to access your apps and desktops.",
        PleaseLogOnToContinue: "Please log on to continue.",
        PopupBlockerDesktopAutoLaunch: "Citrix Receiver has connected your desktop. To see your desktop, allow pop-ups from this website in your browser.",
        PopupBlockerReconnectApps: "Citrix Receiver has reconnected your apps. To see your apps, allow pop-ups from this website in your browser.",
        Preferences: "Preferences",
        ProtocolHandlerUpgradeAvailable: "An upgrade for Citrix Receiver is available. Would you like to download and install it?",

        QuickAccess: "Favorites",

        ReceiverForMac: "Citrix Receiver for Mac",
        ReceiverForWindows: "Citrix Receiver for Windows",
        Refresh: "Refresh",
        RefreshInProgress: "Refreshing apps, please wait.",
        RememberLogonMethod: "Remember my logon method",
        Remove: "Remove",
        Request: "Request",
        ResumingLogon: "Resuming logon, please wait.",
        Restart: "Restart",
        ResourceIsNotAvailable: "\"{0}\" is not available.",
        RetryDownload: "Retry download",
        RetryEpaLaunch: "Retry EPA Launch",

        SearchAppsPlaceholder: "Search All Apps",
        SearchDesktopsPlaceholder: "Search Desktops",
        SearchFavoritesPlaceholder: "Search Favorites",
        SearchPlaceholder: "Search",
        SearchResults: "Search Results ({0})",
        SecurityDetails: "Security details",
        SecurityInformationText: "Whenever you download a file over the Internet, there is always a risk that it will contain a security threat (a virus or a program that can damage your computer and the data stored on it). To check the file for security threats, click Install and then save the file to a suitable location on your computer. Scan the file with an up-to-date antivirus program and carry out any other checks required by your corporate security policy before running/installing the file. You may need to reconfigure the security settings on your computer to install or run the file.",
        SecurityInformationTitle: "SECURITY INFORMATION",
        SessionExpiresInMinutes: "Citrix Receiver will time out in {0} minutes and {1} seconds due to inactivity.",
        SessionExpiresInSeconds: "Citrix Receiver will time out in {0} seconds due to inactivity.",
        SessionsListFailure: "Cannot start your session. Wait a few minutes and try to log on again. If you still experience problems, contact your help desk.",
        SessionTimedOut: "Your session has timed out due to inactivity.",
        SingleApprovedApp: "Your request to add this app is approved.",
        SingleDeniedApp: "Your request to add this app is denied.",
        SkipThisStep: "Click here to skip this step",
        SkipToLogon: "Log on",
        SkipToLogonTip: "Click here to skip to log on",
        SoftwareNotDetected: "Software not detected",
        SoftwareNotDetectedDetails: "Citrix Receiver cannot be detected on your computer. If you know Citrix Receiver is installed, click Continue. If you need assistance, contact your help desk.",
        Start: "Start",
        StartApp: "Start App",
        StartAppMessage: "Please start this app from the Home screen of your phone or tablet.",
        Store: "Store",
        SwitchToExplicit: "Switch to user name and password",
        SwitchToGeneric: "Switch to another authentication method",
        SwitchToSmartcard: "Switch to smart card",

        Tasks: "Tasks",
        ThirdPartyNotices: "Third Party Notices",
        ThirdPartyNoticesWeb: "Citrix Receiver for Web",
        ThirdPartyNoticesHtml5: "Citrix Receiver for HTML5",
        TopRated: "Top Rated",
        TotalRefreshFailure: "Refresh Failed",
        TryAgain: "Try again",
        TryAnotherLogonOption: "Try another logon option",
        TryLater: "Try later",
        TrySearchingInApps: "Try searching in Apps.",

        UnblockCitrixPlugin: "Unblock the Citrix plug-in",
        UnsupportedDevice: "Unsupported device",
        UnsupportedDeviceMessage: "Please use a supported phone, tablet or desktop to access your apps and desktops.",
        Update: "Update",
        UpdatedCat: "Updates Available",
        Upgrade: "Update",
        UpgradeAvailable: "Update available",
        UpgradeCloseBrowser: "You may be asked to close your browser during the installation process.",
        UpgradeInProgress: "Upgrading Citrix Receiver software...",
        UpgradeLater: "Upgrade later",
        UpgradeLaterTip: "Click here to continue without upgrading Citrix Receiver",
        UseAnotherLogonOption: "Use another logon option",
        UseChromeApp: "Use the Citrix Receiver for Chrome App to access this site",
        UseFullVersion: "Use full version",
        UseLightVersion: "Use light version",
        UseReceiver: "Use Citrix Receiver to access your applications and desktops.",
        UsingFullVersion: "You are currently using the full version of Citrix Receiver. Would you like to change to the light version?",
        UsingLightVersion: "You are currently using the light version of Citrix Receiver. Would you like to change to the full version?",

        WaitAppInstallMessage: "Your app will be installed in a few minutes.",
        WaitWhileConfirmInstall: "Please wait while we confirm that Citrix Receiver was installed...",
        WebVersion: "Web version",
        WelcomeToReceiver: "Welcome to Citrix Receiver",
        WhenWindowAppearsLaunchApplication: "When a window appears, choose Launch Application.",

        YouCannotUseAppsOrDesktops: "There are no apps or desktops available to you at this time.",
        YouCannotUseDesktops: "There are no desktops available to you at this time.",
        YouCanUseLightVersion: "If you do not want to detect/install Citrix Receiver you can use the light version, with fewer features, in your browser.",
        YouHaveLoggedOff: "You have logged off successfully.",
        NetscalerGateway: "Citrix Gateway",
        NetscalerAAA: "NetScaler AAA",
        "nsg_username":"User name :",
        "nsg_password1":"Password :",
        "nsg_password2":"Password 2 :",
        "nsg_LogOnbutton":"Log On",
        "nsg_loginHeading":"Please log on",
        "approve_push":"Please approve the notification received on your registered device",
        "End_User_License_Agreement":"End User License Agreement",
        "eula_agreement":"I accept the ",
        "eula_terms":"Terms & Conditions",
        "enter_username_msg":"You need to enter login name",
        "enter_password_msg":"You need to enter a password",
        "enter_passcode_msg":"You need to enter a passcode",
        "enter_question_msg":"You need to enter custom question",
        "enter_answer_msg":"You need to enter all the answers",
        "cert_auth_msg_title":"Certificate Authentication",
        "epa_title":"Citrix Gateway End Point Analysis",
        "postepa_title":"Citrix Gateway End Point Analysis",
        "Epa_checking_msg":"Checking Your Device",
        "Epa_Pre_Reqm_Msg":"Before connecting to your organization's internal network, we need to check that your computer meets certain requirements.",
        "Checking_if_the_plug-in_is_installed":"Checking if the plug-in is installed",
        "epa_download_msg":"You do not have the latest version of Endpoint Analysis plug-in installed. Please download the updated plug-in from the link provided",
        "epa_retry_launch_msg":"Browser couldn't launch the EPA Plug-in on your system. please click on the Retry Launch button to launch EPA plug-in and proceed with the scan.",
        "epa_undetected_msg":"We couldnt detect an EPA Plugin on your system. please click on the download button to install it and proceed.",
        "EPAAccessDenied":"Access Denied",
        "epa_launch_failure_msg":"Endpoint Analysis plug-in is either not launched/installed. Please launch or click on the download link provided.",
        "EPA_not_meet_reqm_msg":"Your device does not meet the requirements for logging on.",
        "EPA_MoreInfoMsg":"For more information, contact your help desk and provide the following information:",
        "EPA_failure_msg":"End point analysis failed",
        "epa_error_msg":"Server encountered an error while processing the request: 0x",
        "epa_config_error_msg":"No matching policy found for processing EPA",
        "Skip Check":"Skip Check",
        "user_skip_epa_msg":"The user skipped the scan",
        "Date":"Date: ",
        "Time":"Time: ",
        "EPAMessaage":"Message: ",
        "secs":"secs",
        "TryAgain":"Try Again",
        "Intranet_IP_Address":"Intranet IP Address",
        "Idle_Time":"Idle Time(H:MM:SS)",
        "nsg_GoBack":"Go Back",
        "nsg-tlogin-heading":"Transfer Logon",
        "nsg-tlogin-transfer":"Transfer",
        "nsg-tlogin-cancel":"Cancel",
        "tlogin_single_res":"You are currently logged on to the Citrix Gateway on another device. Would you like to end that session ?",
        "tlogin_multi_res1":"You have reached the limit of the allowed Citrix Gateway sessions.",
        "tlogin_multi_res2":"Please select which session to release in order to continue with this session.",
        "tlogin_cancel_title":"You have chosen to cancel Transfer Login. Please click on the below button to login again.",
        "LicenseError":"Error: Login exceeds maximum allowed users.",
        "NoIIP":"No IntranetIP available. Please try login later.",
        "GenericError":"The server met an error. Please try again or contact your administrator.",
        "Network_Access": "Network Access",
        "Connect_with_the_AG_Plugin": "Connect with the Citrix Gateway Plug-in",
        "Connect_with_the_AG_Plugin_for_MAC": "Connect with the Citrix Gateway Plug-in for MAC",
        "Clientless_Access": "Clientless Access",
        "Citrix_XenApp": "Virtual App and Desktop Access",
        "agent_description": "Access your organization's resources through a full VPN client with your device. You will be prompted to allow installation of plug-in if not already installed. Use this option only if you are using a trusted device.",
        "cvpn_description": "Select clientless mode to access resources through a web browser. Secure access is limited to the browser window in which you logged on to VPN with. Use this option if you are using an untrusted device.",
        "ica_description": "Select to access your enterprise virtual apps and desktops with Citrix Receiver.",
        "ClientchoicesTitle": "Please select one of the following:",
        "Citrix_Access_Gateway": "Citrix Gateway",
        "If_the_Access_Gateway_Plugin_is_installed": "If the Citrix Gateway Plug-in is installed and not running, click \"Start &amp;gt; All Programs &amp;gt; Citrix &amp;gt; Citrix Gateway\" to start the application.",
        "vpn_waitingmsg": "Please wait for the VPN session to be established.",
        "If_a_proxy_server_is_configured": "If a proxy server is configured, you need to add \"localhost\" to the proxy exception in your Web browser.",
        "For_more_information_contact_your_help_desk_or_system_administrator": "For more information contact your help desk or system administrator.",
        "To_install_the_Access_Gateway_Plugin": "To install the Citrix Gateway Plug-in:",
        "Click_Download": "1.  Click <B>Download<B>.",
        "To_install_the_Netscaler_Access_Gateway_Client_for_Linux":"To install the Citrix Gateway Client for Linux (currently supported on Ubuntu OS)",
        "If_the_Access_Gateway_Plug-in_is_not_installed":"The Citrix Gateway Plug-in is either not installed or requires updating.",
		"Your_administrator_requires_you_to_use_CSA":"Your administrator requires you to use Citrix Secure Access for authentication and access.",
        "To_install_the_Netscaler_Access_Gateway_Client_for_Mac":"Navigate to the App Store, search for Citrix Secure Access, and select Get to download.",
		"Contact_your_system_administrator":"If issues persist, contact your system administrator.",
        "Linux_install_using_software_center":"2.  Install the downloaded debian package using Ubuntu Software Center",
        "In_the_File_Download_dialog_box_click_Run": "2.  In the File Download dialog box, click <B>Run</B>.",
        "In_the_Internet_Explorer_dialog_box_click_Run_to_install_the_Access_Gateway_Plugin_for_Windows": "3.  In the browser dialog box, click <B>Run</B> to install the Citrix Gateway Plug-in for Windows.",
        "cvpn_wait_msg":"Loading your Apps...",
        "RDP_hint" : "The checkbox 'RDP Link' needs to be checked in case a RDP link is being added or being accessed using Go button.",
        "PB_url":"URL<sup>*</sup>:",
        "PB_name":"Name<sup>*</sup> :",
        "PB_description":"Description :",
        "Enter_url_placeholder":"Enter URL",
        "Enter_name_placeholder":"Choose Name",
        "Enter_description_placeholder":"Add your Description",
        "save":"Save",
        "Go":"Go",
        "Delete":"Delete",
        "Bookmark":"Bookmark",
        "rdplinkChecklabel":"RDP Link",
        "Allow_popups":"Please allow popups in your browser to be able to view the url in new tab.",
        "Personal_Bookmark":"Personal Bookmark",
        "PersonalBookmark_error1" : "You must provide a URL for your bookmark.",
        "PersonalBookmark_error2" : "Please provide a name for your bookmark.",
        "PersonalBookmark_error3" :  "The bookmark contains invalid URI characters. Please enter a valid Web address.",
        "NsgEmail_AppName":"Email Home",
        "PersonalBookmark_error4":"Please enter a URL first.",
        "errorMessageLabel4444":"Incorrect user name or password.",
        "errorMessageLabel4001":"Incorrect user name or password.",
        "errorMessageLabel4002":"You do not have permission to log on.",
        "errorMessageLabel4003":"Cannot connect to server. Try connecting again in a few minutes.",
        "errorMessageLabel4004":"Cannot connect. Try connecting again.",
        "errorMessageLabel4005":"Cannot connect. Try connecting again.",
        "errorMessageLabel4006":"Incorrect user name.",
        "errorMessageLabel4007":"Incorrect password.",
        "errorMessageLabel4008":"Passwords do not match.",
        "errorMessageLabel4009":"User not found.",
        "errorMessageLabel4010":"You do not have permission to log on at this time.",
        "errorMessageLabel4011":"Your account is disabled.",
        "errorMessageLabel4012":"Your password has expired.",
        "errorMessageLabel4013":"You do not have permission to log on.",
        "errorMessageLabel4014":"Could not change your password.",
        "errorMessageLabel4015":"Your account is temporarily locked.",
        "errorMessageLabel4016":"Could not update your password. The password must meet the length, complexity, and history requirements of the domain.",
        "Admin_apps_bundle_descr":"Apps delivered by Gateway",
        "Admin_apps_bundle_title":"Web and SaaS Apps",
        "Personal_apps_bundle_descr":"Personal Web Bookmarks",
        "Personal_apps_bundle_title":"Personal Bookmarks",
        "Admin_apps_title":"Citrix Gateway Bookmarks",
        "Personal_apps_title":"Personal Bookmarks",
        "vmware_bundle_descr":"Apps from VMware",
        "vmware_bundle_title":"VMware Apps",
        "vmware_apps_title":"VMware Apps",
        "vmware_missing_title":"VMware client missing",
        "vmware_install_reqd_msg":"Please install the VMware Horizon Client",
	    "MaxLoginAttempts":"You have exceeded the maximum login attempts.",
	    "NoClientChoices":"There are no access modes available to you at this time. Please contact your help desk",
	    "NoPrimaryAuthPol":"No active policy is found in Primary authentication cascade. Please contact your help desk",
        "NoSecondaryAuthPol":"No active policy is found in Secondary authentication cascade. Please contact your help desk",
        "NoTertiaryAuthPol":"No active policy is found in Tertiary authentication cascade. Please contact your help desk",
        "IncorrectCapabilities":"The client is not capable of connecting to this server. Please contact your help desk",
        /* OTP Management Messages */
        "Done": "Done",
        "OTPDeleteAllSuccess": "Successfully deleted all registered devices",
        "OTPDeleteAllFailure": "Failed to delete all devices",
        "OTPDeleteDeviceSuccess" : "Successfully deleted {0}",
        "OTPDeleteDeviceFailure" : "Failed to delete {0}",
        "OTPConfirmDelete" : "Confirm Delete",
        "Yes": "Yes",
        "No": "No",
        "OTPDeleteAllConfirm": "Are you sure you want to delete ALL registered devices?",
        "OTPDeleteDeviceConfirm": "Are you sure you want to delete {0}?",
        "OTPCode": "Scan QR or type the following code {0}",
        "OTPAddSuccess": "Added {0} successfully!",
        "OTPAddFailure": "Failed to add {0}",
        "OTPDeviceExists": "Device '{0}' already exists",
        "OTPEnterName": "Enter a device name to add",
        "OTPTestSuccess": "Successfully verified OTP from {0}",
        "OTPTestFailure": "Failed to verify OTP from {0}. Please ensure Citrix ADC is synced to NTP time.",
        "OTPEnterTestValue": "Enter OTP value to test",
        "OTPDeleteAll": "Delete ALL",
        "OTPAddDeviceToolTip": "Add Device",
        "OTPTestDeviceToolTip": "Test Device",
        "OTPRegisteredDevices": "My Registered Devices",
        "OTPNoDevices": "No registered devices",
        "OTPTest": "Test",
        "OTPQRError":"Could not load ReCaptcha. Please contact your administrator.",
        "OTPAddMaxDevices":"You have reached maximum number of devices permitted.",
        /* OTP Management Messages End*/
	/* nFactor messages begin */
	"Invalid Credentials": "Invalid Credentials",
	"Not Permitted": "Not Permitted",
	"System Timeout": "System Timeout",
	"System Error": "System Error",
	"Socket Error": "Socket Error",
	"Bad User": "Bad User",
	"Bad Password": "Bad Password",
	"Password Mismatch": "Password Mismatch",
	"No such user": "No such user",
	"Restricted Hours": "Restricted Hours",
	"Account Disabled": "Account Disabled",
	"Password Expired": "Password Expired",
	"No dial-in permission": "No dial-in permission",
	"Changing Password": "Changing Password",
	"Account Locked": "Account Locked",
	"Constraint violation": "Constraint violation",
	"Try again after some time or contact your help desk": "Try again after some time or contact your help desk",
	"Certificate not presented by user": "Certificate not presented by user",
	"Renegotiation of certificate failed": "Renegotiation of certificate failed",
	"Invalid certificate is presented": "Invalid certificate is presented",
	"Error trying to extract artifact from certificate": "Error trying to extract artifact from certificate",
	"No active policy during authentication": "No active policy during authentication",
	"No active policy while trying to fallback from certificate failure": "No active policy while trying to fallback from certificate failure",
	"No active policy while trying to fallback from Negotiate/NTLM failure": "No active policy while trying to fallback from Negotiate/NTLM failure",
	"You are not allowed to login. Please contact administrator": "You are not allowed to login. Please contact administrator",
	"You have exceeded the maximum login attempts. Please contact administrator": "You have exceeded the maximum login attempts. Please contact administrator",
	"Netscaler unable to contact server for NTLM authentication. Please contact administrator": "Citrix ADC unable to contact server for NTLM authentication. Please contact administrator",
	"Target URL not found for redirect after successful login. Please contact your administrator.": "Target URL not found for redirect after successful login. Please contact your administrator.",
	"EPA Factor is mutually exclusive with EPA at vserver": "EPA Factor is mutually exclusive with EPA at vserver",
	"No active policy to begin EPA": "No active policy to begin EPA",
	"Session absent to manage otp for user, probably misconfiguration. Please contact your adminsitrator.": "Session absent to manage otp for user, probably misconfiguration. Please contact your adminsitrator.",
	/* nFactor messages end */
	"nsg_oldpass": "Old Password :",
	"nsg_newpass": "New Password :",
	"nsg_confirmpass": "Confirm Password :",
	"nsg_changepass": "Change Password",
	"ns_dialogue": "Password",
	"ns_DialogSubmit": "Submit",
	"Password change failed. Make sure you supply correct existing password and try again.": "Password change failed. Make sure you supply correct existing password and try again.",
	"Gateway encountered an unexpected condition. Please contact your admin for details": "Citrix Gateway encountered an unexpected condition. Please contact your admin for details",
	"You are not allowed to change the password. Please contact your admin for details.": "You are not allowed to change the password. Please contact your admin for details.",
	"One of the fields is empty. Please enter your password, and new password twice.": "One of the fields is empty. Please enter your password, and new password twice.",
	"The passwords you typed do not match. Please try again.": "The passwords you typed do not match. Please try again.",

    // Login schema localisation changes
    "checkbox_accept_terms_and_conditions": "Accept terms and conditions",
  "checkbox_log_on": "Log On",
  "checkbox_password": "Password:",
  "checkbox_please_enter_username": "Please enter username",
  "checkbox_user_name": "User Name:",
  "clientcertdualauthdeviceid_": "",
  "clientcertdualauthdeviceid_passcode": "Passcode:",
  "clientcertdualauthdeviceid_password": "Password:",
  "clientcertdualauthdeviceid_please_log_on": "Please log on",
  "clientcertdualauthdeviceid_remember_my_credentials": "Remember my credentials",
  "clientcertdualauthdeviceid_submit": "Submit",
  "clientcertdualauthdeviceid_user_name": "User name:",
  "clientcertsingleauthdeviceid_first_factor": "First factor",
  "clientcertsingleauthdeviceid_log_on": "Log On",
  "clientcertsingleauthdeviceid_password": "Password:",
  "clientcertsingleauthdeviceid_please_supply_either_domain\\username_or_user@fully.qualified.domain": "Please supply either domain\\username or user@fully.qualified.domain",
  "clientcertsingleauthdeviceid_remember_my_password": "Remember my password",
  "clientcertsingleauthdeviceid_user_name": "User name:",
  "domaindropdown_(select_a_domain)": "(Select a domain)",
  "domaindropdown_aaatm.com": "AAATM.COM",
  "domaindropdown_log_on": "Log On",
  "domaindropdown_nsi-test.com": "NSI-TEST.COM",
  "domaindropdown_password": "Password:",
  "domaindropdown_please_select_domain_to_continue_login_...": " Please select domain to continue Login ...",
  "domaindropdown_please_supply_either_domain\\username_or_user@fully.qualified.domain": "Please supply either domain\\username or user@fully.qualified.domain",
  "domaindropdown_user_name": "User name:",
  "dualauth_": "",
  "dualauth_flipped_": "",
  "dualauth_flipped_passcode": "Passcode:",
  "dualauth_flipped_password": "Password:",
  "dualauth_flipped_please_log_on": "Please log on",
  "dualauth_flipped_remember_my_credentials": "Remember my credentials",
  "dualauth_flipped_submit": "Submit",
  "dualauth_flipped_user_name": "User name:",
  "dualauth_passcode": "Passcode:",
  "dualauth_password": "Password:",
  "dualauth_please_log_on": "Please log on",
  "dualauth_remember_my_credentials": "Remember my credentials",
  "dualauth_submit": "Submit",
  "dualauth_user_name": "User name:",
  "dualauthdeviceid_": "",
  "dualauthdeviceid_passcode": "Passcode:",
  "dualauthdeviceid_password": "Password:",
  "dualauthdeviceid_please_log_on": "Please log on",
  "dualauthdeviceid_remember_my_credentials": "Remember my credentials",
  "dualauthdeviceid_submit": "Submit",
  "dualauthdeviceid_user_name": "User name:",
  "dualauthorotpregisterdynamic_": "",
  "dualauthorotpregisterdynamic_click_to_register": "Click to register",
  "dualauthorotpregisterdynamic_devicename": "DeviceName:",
  "dualauthorotpregisterdynamic_passcode": "Passcode:",
  "dualauthorotpregisterdynamic_password": "Password:",
  "dualauthorotpregisterdynamic_please_log_on": "Please log on",
  "dualauthorotpregisterdynamic_remember_my_credentials": "Remember my credentials",
  "dualauthorotpregisterdynamic_submit": "Submit",
  "dualauthorotpregisterdynamic_user_name": "User name:",
  "dualauthorpush_please_log_on": "Please log on",
  "dualauthorpush_user_name": "User name:",
  "dualauthorpush_password": "Password:",
  "dualauthorpush_vip_or_totp": "VIP or TOTP:",
  "dualauthorpush_click_to_use_push": "Click to use Push",
  "dualauthorpush_submit": "Submit",
  "onlydomaindropdown_(select_a_domain)": "(Select a domain)",
  "onlydomaindropdown_aaatm.com": "AAATM.COM",
  "onlydomaindropdown_citrix.com": "CITRIX.COM",
  "onlydomaindropdown_log_on": "Log On",
  "onlydomaindropdown_nsi-test.com": "NSI-TEST.COM",
  "onlydomaindropdown_please_select_domain_to_continue_login_...": " Please select domain to continue Login ...",
  "onlyotpregistration_device_name_for_managing_secret": "Device name for managing secret",
  "onlyotpregistration_mobile": "mobile",
  "onlyotpregistration_devicename": "DeviceName:",
  "onlyotpregistration_please_log_on": "Please log on",
  "onlyotpregistration_submit": "Submit",
  "onlyotpregistration_user_name": "User name:",
  "onlypassword_please_enter_password_for_step_up_auth":" Please enter password for step up auth.",
  "onlypassword_hello":"Hello, ",
  "onlypassword_hello_please_enter_password_for_step_up_auth": "Hello, Please enter password for step up auth.",
  "onlypassword_log_on": "Log On",
  "onlypassword_password": "Password:",
  "onlypassword_remember_my_password": "Remember my password",
  "onlyusername_log_on": "Log On",
  "onlyusername_please_enter_username_...": " Please enter UserName ...",
  "onlyusername_please_supply_either_username_as_saamaccountname": "Please supply either username as samaccountname",
  "onlyusername_remember_my_password": "Remember my password",
  "onlyusername_user_name": "User name:",
  "pass_enc_encryption_failed_header":"The password encryption failed",
  "pass_enc_encryption_failed_message":"The password encryption failed. To continue with your log on, disable password encryption.",
  "pass_enc_unsupported_browser_header":"Unsupported Browser for Encryption",
  "pass_enc_unsupported_browser_message":"Password encryption is not supported on your browser. For the list of browsers and versions that support password encryption, please refer Citrix documentation",
  "prefiluserfromexpr_log_on": "Log On",
  "prefiluserfromexpr_password": "Password:",
  "prefiluserfromexpr_please_supply_either_domain\\username_or_user@fully.qualified.domain": "Please supply either domain\\username or user@fully.qualified.domain",
  "prefiluserfromexpr_remember_my_password": "Remember my password",
  "prefiluserfromexpr_second_factor": "Second factor",
  "prefiluserfromexpr_user_name": "User name:",
  "singleauth_first_factor": "First factor",
  "singleauth_log_on": "Log On",
  "singleauth_password": "Password:",
  "singleauth_please_supply_either_domain\\username_or_user@fully.qualified.domain": "Please supply either domain\\username or user@fully.qualified.domain",
  "singleauth_remember_my_password": "Remember my password",
  "singleauth_user_name": "User name:",
  "singleauthcaptcha_captcha": "Captcha:",
  "singleauthcaptcha_log_on": "Log On",
  "singleauthcaptcha_password": "Password:",
  "singleauthcaptcha_please_enter_your_credentials_and_verify_captcha": "Please enter your credentials and verify captcha",
  "singleauthcaptcha_please_supply_either_domain\\username_or_user@fully.qualified.domain": "Please supply either domain\\username or user@fully.qualified.domain",
  "singleauthcaptcha_remember_my_password": "Remember my password",
  "singleauthcaptcha_user_name": "User name:",
  "dualauthcaptcha_captcha": "Captcha:",
  "dualauthcaptcha_log_on": "Log On",
  "dualauthcaptcha_password": "Password:",
  "dualauthcaptcha_passcode": "Passcode:",
  "dualauthcaptcha_please_enter_your_credentials_and_verify_captcha": "Please enter your credentials and verify captcha",
  "dualauthcaptcha_please_supply_either_domain\\username_or_user@fully.qualified.domain": "Please supply either domain\\username or user@fully.qualified.domain",
  "dualauthcaptcha_remember_my_password": "Remember my password",
  "dualauthcaptcha_user_name": "User name:",
  "singleauthdeviceid_first_factor": "First factor",
  "singleauthdeviceid_log_on": "Log On",
  "singleauthdeviceid_password": "Password:",
  "singleauthdeviceid_please_supply_either_domain\\username_or_user@fully.qualified.domain": "Please supply either domain\\username or user@fully.qualified.domain",
  "singleauthdeviceid_remember_my_password": "Remember my password",
  "singleauthdeviceid_user_name": "User name:",
  "singleauthmanageotp_password": "Password:",
  "singleauthmanageotp_please_log_on": "Please log on",
  "singleauthmanageotp_submit": "Submit",
  "singleauthmanageotp_user_name": "User name:",
  "singleauthdopush_please_logon": "Please log on",
  "singleauthdopush_username": "User name:",
  "singleauthdopush_password": "Password:",
  "singleauthdopush_submit": "Submit",
  "singleauthpasswordreset_first_factor": "First factor",
  "singleauthpasswordreset_submit": "Submit",
  "singleauthpasswordreset_password": "Password:",
  "singleauthpasswordreset_please_supply_either_domain\\username_or_user@fully.qualified.domain": "Domain\\username or user@domain.com",
  "singleauthpasswordreset_remember_my_password": "Remember my password",
  "singleauthpasswordreset_user_name": "User name:",
  "singleauthpasswordreset_forgot_password": "Forgot Password",
  "dualauthpasswordreset_": "",
  "dualauthpasswordreset_passcode": "Passcode:",
  "dualauthpasswordreset_password": "Password:",
  "dualauthpasswordreset_please_log_on": "Please log on",
  "dualauthpasswordreset_remember_my_credentials": "Remember my credentials",
  "dualauthpasswordreset_submit": "Submit",
  "dualauthpasswordreset_user_name": "User name:",
  "dualauthpasswordreset_forgot_password": "Forgot Password",
  "ForgotPassword" : "Forgot Password",
  "waitMessage" : "Your request is being processed",
  "sspr_password_reset_successful" : "Password reset successful",
  "nsg_kba_registration_heading" : "KBA Registration",
  "email_registration_heading" : "Email Registration",
  "alternate_email_id" : "Alternate Email Id",
  "EmailOTP" : "Enter OTP from Email",
  "kba_invalide_qora" : "Invalid Question/Answer",
  "emailotp_invalid_code" : "Invalid OTP Code. Email Auth failed; No further action to continue.",
  "nsg_kba_question" : "Question",
  "nsg_kba_answer" : "Answer",
  "dualauthpushorotp_please_log_on": "Please log on",
  "dualauthpushorotp_user_name": "User name:",
  "dualauthpushorotp_password": "Password:",
  "dualauthpushorotp_vip_or_totp": "VIP or OTP:",
  "dualauthpushorotp_click_to_use_otp": "Click to input OTP manually",
  "dualauthpushorotp_submit": "Submit",
  "KB Questions and Answers not registered":"KB Questions and Answers not registered",
  "Question":"Question",
  "Answer":"Answer",
  "OTPDeleteDevice":"Scan QR Code into the CitrixSSO App"
    });
})(jQuery);
